acc/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_delete/', views.user_delete, name="user_delete"),

    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('chpass/', views.chpass, name='chpass'),
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<bpk>', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('tts/', include('tts.urls')),
    path('todo/', include('todo.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('detail/<vpk>', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('vote/<vpk>', views.vote, name='vote'),

    path('delete/<vpk>', views.delete, name='delete'),
    path('cancel/<vpk>', views.cancel, name='cancel')
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    title = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='maker')
    content = models.TextField()
    pic = models.ImageField(upload_to='vote/%y/%m')
    voter = models.ManyToManyField(User, blank=True, related_name='voter')

    def __str__(self):
        return self.title
    
    def getpic(self):
        if self.pic:
            return self.pic.url
        
        return "/media/noimage.png"
    

class Choice(models.Model):
    top = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField(default='')
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f'{self.top}_{self.name}'

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
from django.contrib import messages

# Create your views here.
def index(request):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    t = Topic.objects.all()

    context = {
        'tset' : t
    }

    return render(request, 'vote/index.html', context)

def detail(request, vpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    t = Topic.objects.get(id=vpk)
    c = t.choice_set.all()

    context = {
        't' : t,
        'cset' : c
    }
    

    return render(request, 'vote/detail.html', context)

def create(request):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    if request.method == 'POST':
        nm = request.POST.get('title')
        con = request.POST.get('det')
        pic = request.FILES.get('pic')
        cn = request.POST.getlist('con')
        cc = request.POST.getlist('com')

        t = Topic(title=nm, maker=request.user, content=con, pic=pic)
        t.save()

        for i, j in zip(cn, cc):
            Choice(top=t, name=i, comment=j).save()

        return redirect('vote:index')

    return render(request, 'vote/create.html')

def vote(request, vpk): 
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    t = Topic.objects.get(id=vpk)

    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get('cho')
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
        c.save()
    
    return redirect('vote:detail', vpk)

def delete(request, vpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    t = Topic.objects.get(id=vpk)

    if request.user == t.maker:
        t.pic.delete()
        t.delete()
    else:
        messages.error(request, '이거 니꺼 아니니깐 지우지 마세요')
    
    return redirect('vote:index')

def cancel(request, vpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    t = Topic.objects.get(id=vpk)
    u = request.user
    t.voter.remove(u)
    u.choice_set.get(top=t).choicer.remove(u)

        
    
    return redirect('vote:detail', vpk)

templates/vote/create.html
{% extends 'base.html' %}

{% block con %}

<div class="container">

    <h1><b>토픽생성</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="text" placeholder="INPUT SUBJECT" class="form-control mt-5" name="title">
        <input type="text" value="{{user}}" disabled class="form-control mt-3 mb-3">
        <textarea class="form-control" style="height: 200px;" placeholder="INPUT CONTENT" name="det"></textarea><br>
        <input type="file" name="pic" class="form-control">

        <div class="text-end mt-4">
            <button type="button" onclick="makecho()" class="btn btn-dark">보기생성</button>
            <button class="btn btn-dark">토픽생성</button>
        </div>

        <div id="here" class="row mt-5"></div>

    </form>


    <script>
        function makecho(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-sm-4");
            n.innerHTML = "<input type='text' placeholder='INPUT NAME' class='form-control' name='con'>\
            <textarea class='form-control mt-3 mb-5' placeholder='INPUT COMMENT' name='com'></textarea>";
            d.appendChild(n);
        }
    </script>



</div>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}

{% block con %}

{% load mathfilters %}

<div class="container">

    <h1><b>{{t.title}}</b></h1>


    <div class="row mt-4">
        <div class="col-sm-9">
            <textarea class="form-control" style="height:250px" disabled>{{t.content}}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{t.maker.getpic}}" width="100%">
            <div class="mt-3 text-center">
                <h4>made by <b>{{t.maker}}</b></h4>
            </div>
        </div>
    </div>

    <hr>

    {% if user in t.voter.all %}
        <div class="row mt-5">
            {% for i in cset %}
            
            <div class="col-sm-4">
                <label class="form-check-label">
                    <h4><b>{{i.name}}</b></h4>
                </label>
                <div class="progress mt-3 mb-3" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%">{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }} %</div>
                </div>
                <textarea class="form-control mt-3" style="height: 100px;" disabled>{{i.comment}}</textarea>
            </div>
            {% endfor %}
        </div>
        <div class="text-end mt-4">
            <a href="{% url 'vote:cancel' t.id %}" class="btn btn-danger">무르기</a>
        </div>



    {% else %}
    <div class="row mt-5">
        {% for i in cset %}
        <div class="col-sm-4">
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
            <input type="radio" class="form-check-input" name="cho" value="{{i.id}}">
            <label class="form-check-label">
                <h4><b>{{i.name}}</b></h4>
            </label>
            <textarea class="form-control mt-3" style="height: 100px;" disabled>{{i.comment}}</textarea>
            
        </div>
        {% endfor %}
    </div>
    <div class="text-end mt-4">
        <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#books">
            ✨
        </button>
        <button class="btn btn-dark">투표하기</button>
    </div>
</form>

    {% endif %}
    
</div>

<div class="modal fade" id="books" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel"><b>북마크 추가</b></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <form method="post" action="{% url 'book:create' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off" name="ip">
                    <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br><br>
                    <textarea class="form-control" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;" name="con"></textarea>

                    <input type="hidden" name="nm" value="[VOTE]::{{t.title}}">
                    <input type="hidden" name="url" value="{{request.path}}">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-primary">추가</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}

{% block con %}
<div class="container">

    <h1><b>투표소</b></h1>

    <div class="text-end">
        <a href="{% url 'vote:create' %}" class='btn btn-dark btn-lg'>+TOPIC</a>
    </div>

    <div class="row">
        {% for i in tset %}
        <div class="col-sm-4">
            <div class="card text-center">
                <img src="{{i.getpic}}" class="card-img-top">
                <div class="card-body" {% if user in i.voter.all %} style="background-color: rgb(250, 235, 215);" {% endif %}>
                    <h4 class="card-title"><b>{{i.title}}</b></h4>
                    <p class="card-text">{{i.content|truncatewords:10}}</p>
                    <a href="{% url 'vote:detail' i.id %}" class="btn btn-outline-dark">
                        {% if user in i.voter.all %}결과보기{% else %}투표하기{% endif %}
                    </a>
                    {% if user == i.maker %}
                    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#e{{forloop.counter}}">
                        삭제하기
                    </button>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}

        <h3 class="text-center">토픽을 생성해보세요!</h3>
        {% endfor %}

    </div>

    <!-- Modal -->
    {% for i in tset %}
    <div class="modal fade" id="e{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel"><b>{{ i.subject }}</b> 토픽 삭제 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <mark><b>{{i.voter.count}}</b></mark>명이 참여한 투표입니다. 그래도 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">창 닫기</button>
                    <a href="{% url 'vote:delete' i.id %}" type="button" class="btn btn-danger">삭제하기</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}