acc/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_delete/', views.user_delete, name="user_delete"),

    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('chpass/', views.chpass, name='chpass'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('tts/', include('tts.urls')),
    path('todo/', include('todo.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    age = models.IntegerField(default=0)
    pic = models.ImageField(upload_to='usr/%y/%m')
    comment = models.TextField()

    def getpic(self):
        if self.pic:
            return self.pic.url
        
        return '/media/noimage.png'

acc/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import check_password
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'acc/index.html')

def signup(request):
    if request.user.is_authenticated:
        return redirect('acc:index')

    if request.method == 'POST':
        pw = request.POST.get('password1')
        un = request.POST.get('username')
        up = request.FILES.get('userpic')
        uc = request.POST.get('comment')
        ua = request.POST.get('age')

        User.objects.create_user(username=un, password=pw, pic=up, comment=uc, age=ua)

        return redirect('acc:user_login')


    return render(request, 'acc/signup.html')

def user_login(request):
    if request.user.is_authenticated:
        return redirect('acc:index')

    if request.method == 'POST':
        un = request.POST.get('username')
        pw = request.POST.get('password')

        u = authenticate(username=un, password=pw)

        if u:
            login(request, u)
            messages.success(request, f'{u}님, 환영합니다!')
        else:
            messages.info(request, '계정 정보가 일치하지 않습니다')

        return redirect('acc:user_login')

    return render(request, 'acc/login.html')

def user_logout(request):
    if not request.user.is_authenticated:
        return redirect('acc:index')

    logout(request)
    return redirect('acc:index')

def profile(request):
    if not request.user.is_authenticated:
        return redirect('acc:index')

    return render(request, 'acc/profile.html')

def user_delete(request):
    if not request.user.is_authenticated:
        return redirect('acc:index')
    
    if request.method == 'POST':
        up = request.POST.get('password')
        upw = request.user.password

        if check_password(up, upw):
            u = request.user

            if u.pic:
                u.pic.delete()

            u.delete()
            return redirect('acc:index')
        
    return redirect('acc:index')

def update(request):
    if not request.user.is_authenticated:
        return redirect('acc:index')

    if request.method == 'POST':
        u = request.user

        u.pic.delete()

        up = request.FILES.get('userpic')
        ue = request.POST.get('email')
        uc = request.POST.get('comment')
        ua = request.POST.get('age')

        u.pic, u.comment, u.age, u.email = up, uc, ua, ue
        u.save()

        return redirect('acc:profile')

    return render(request, 'acc/update.html')

def chpass(request):
    if not request.user.is_authenticated:
        return redirect('acc:index')

    if request.method == 'POST':
        u = request.user
        old_pw = request.POST.get('cpw')
        qwe_pw = u.password
        up = request.POST.get('npw')

        if check_password(old_pw, qwe_pw):
            u.set_password(up)
            u.save()
            return redirect('acc:user_login')
        

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
    
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">WELCOME TO MY WEBSITE!</h1>
        <p class="col-md-8 fs-4">Hello everyone! My first django project 💥 </p>
    </div>
</div>


{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block con %}

<h1><b>LOGIN PAGE</b></h1>

<form method="post">
    {% csrf_token %}

    <input type="text" class="form-control mt-5" placeholder="INPUT USERNAME" name="username">
    <input type="password" class="form-control mt-3" placeholder="INPUT PASSWORD" name="password">

    <div class="text-end mt-4">
        <button class="btn btn-dark btn-lg">LOGIN</button>
    </div>

</form>




{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}

{% block con %}

<div class="container mt-5 mb-5">
    <h1><b>{{ user }}'s PROFILE</b></h1>

    <div class="row">
        <div class="col-sm-7 text-center" style="margin: auto;">
            <img src="{{ user.getpic }}" class="rounded-circle" width="80%">
        </div>
        <div class="col-sm-5">

            <label class="form-label mt-5">USERNAME</label>
            <input type="text" disabled class="form-control" value="{{ user.username }}">
    
            <label class="form-label mt-4">AGE</label>
            <input type="text" disabled class="form-control" value="{{ user.age }}">
    
            <label class="form-label mt-4">EMAIL</label>
            <input type="text" disabled class="form-control" value="{{ user.email }}">

            <label class="form-label mt-4">COMMENT</label>
            <textarea class="form-control" disabled>{{ user.comment }}</textarea>
        </div>
    </div>

    <div class="mt-5 text-end">
        <a href="{% url 'acc:update' %}" class="btn btn-dark btn-lg">정보수정</a>
        <!-- modal trigger button -->
        <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
            계정삭제
        </button>
    </div>
    
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">계정 삭제 알림창</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'acc:user_delete' %}">
                <div class="modal-body">
                        {% csrf_token %}
                        <label class="form-label">패스워드 확인</label>
                        <input type="password" class="form-control" name="password">
                
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-danger">삭제</button>
                    
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block con %}

<h1><b>SIGNUP PAGE</b></h1>


<form method="post" enctype="multipart/form-data" name="signup">
    {% csrf_token %}


    <label class="form-label mt-5">USERNAME</label>
    <input type="text" class="form-control" name="username">
    
    <label class="form-label mt-4">PASSWORD</label>
    <input type="password" class="form-control" name="password1">
    
    <label class="form-label mt-4">CHECK PASSWORD</label>
    <input type="password" class="form-control" name="password2">
    
    <label class="form-label mt-4">USERPIC</label>
    <input type="file" class="form-control" name="userpic">

    <label class="form-label mt-5">AGE</label>
    <input type="number" class="form-control" name="age" value="0">
    
    <label class="form-label mt-4">COMMENT</label>
    <textarea class="form-control" name="comment"></textarea> 
    
    <div class="text-end mt-4">
        <button type="button" class="btn btn-dark btn-lg" onclick="passcheck()">회원가입</button>
    </div>

</form>

<script>
    function passcheck(){
        cf = document.signup;

        const p1 = cf.password1.value;
        const p2 = cf.password2.value;

        if (p1 !== p2){
            alert("비밀번호가 틀렸습니다")
        } else {
            cf.submit()
        }
    }
</script>


{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}

{% block con %}

<h1><b>UPDATE PAGE</b></h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- username 은 변경불가하도록 disabled 유지 -->
    <label class="form-label mt-5">USERNAME</label>
    <input type="text" disabled value="{{user}}" class="form-control">

    <label class="form-label mt-4">EMAIL</label>
    <input type="text" value="{{user.email}}" class="form-control" name="email">

    <label class="form-label mt-4">AGE</label>
    <input type="text" value="{{user.age}}" class="form-control" name="age">

    <label class="form-label mt-4">USERPIC</label>
    <input type="file" class="form-control" name="userpic">

    <label class="form-label mt-4">COMMENT</label>
    <textarea class="form-control" name="comment">{{ user.comment }}</textarea> 

    <div class="text-end mt-4">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
            패스워드변경
        </button>
        <button class="btn btn-dark btn-lg">수정완료</button>
    </div>
</form>




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel"><b>패스워드 변경창</b></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'acc:chpass' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="password" placeholder="CURRENT PASSWORD" class="form-control" name="cpw">
                    <input type="password" placeholder="NEW PASSWORD" class="form-control mt-3" name="npw">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-primary">변경</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}