acc/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_delete/', views.user_delete, name="user_delete"),

    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('chpass/', views.chpass, name='chpass'),
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<bpk>', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('tts/', include('tts.urls')),
    path('todo/', include('todo.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('finish/<tpk>', views.finish, name='finish'),
    path('delete/<tpk>', views.delete, name='delete'),
]

tts/urls.py
from django.urls import path
from . import views

app_name = 'tts'

urlpatterns = [
    path('index/', views.index, name='index'),
]

vote/urls.py
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('detail/<vpk>', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('vote/<vpk>', views.vote, name='vote'),

    path('delete/<vpk>', views.delete, name='delete'),
    path('cancel/<vpk>', views.cancel, name='cancel')
]

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        {% if user.is_authenticated %}
        <!-- 인증된 사용자 메뉴바 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0);">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:index' %}">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'trans:index' %}">TRANS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'tts:index' %}">TTS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'vote:index' %}">VOTE</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'todo:index' %}">TODO</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'book:index' %}">BOOKMARK</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:user_logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="navbar-text clock">
                            <div class="TimeZone">
                                <span id="what"></span>
                                <span id="hours"></span> :
                                <span id="min"></span> :
                                <span id="sec"></span>
                            </div>
                            <div class="Datezone">
                                <span id="year"></span>년
                                <span id="month"></span>월
                                <span id="date"></span>일
                                <span id="day"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        {% else %}
        <!-- 익명의 사용자 메뉴바 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0);">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:index' %}">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:user_login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                        <div class="navbar-text clock">
                            <div class="TimeZone">
                                <span id="what"></span>
                                <span id="hours"></span>시
                                <span id="min"></span>분
                                <span id="sec"></span>초
                            </div>
                            <div class="Datezone">
                                <span id="year"></span>년
                                <span id="month"></span>월
                                <span id="date"></span>일
                                <span id="day"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        {% endif %}

        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
            <symbol id="info-fill" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
            <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>

        {% for i in messages %}
            {% if i.tags == 'info' %}
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:" style="height:20px; width:20px;"><use xlink:href="#info-fill"/></svg>
                <div>
                    {{ i.message }}
                </div>
            </div>

            {% elif i.tags == 'warning' %}
            <div class="alert alert-warning d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Warning:" style="height:20px; width:20px;"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <div>
                    {{ i.message }}
                </div>
            </div>

            {% elif i.tags == 'success' %}
            <div class="alert alert-success d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:" style="height:20px; width:20px;"><use xlink:href="#check-circle-fill"/></svg>
                <div>
                    {{ i.message }}
                </div>
              </div>

            {% elif i.tags == 'error' %}
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:" style="height:20px; width:20px;"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <div>
                    {{ i.message }}
                </div>
            </div>


            {% endif %}
        {% endfor %}

        <div class="container mt-5 mb-5">
        <!-- 본문들어갈곳! -->
        </div>
            {% block con %}
            {% endblock %}
        
        <style>
            .nav-item{
                font-size: 20px;
                font-weight: bold;
                margin-left: 10px;
            }
            .form-control{
                font-weight: bold;
                font-size: 20px;
            }
            .form-label{
                font-weight: bold;
                font-size: 20px;
            }

            .mark{
                background-color: black;
            }
        </style>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
        </script>

        <script>
            	
            var clockStart = setInterval(function() {
                var today = new Date()
                var dayList = ["일","월","화","수","목","금","토"]
            
                var hh = addZero(today.getHours())
                var mm = addZero(today.getMinutes())
                var ss = addZero(today.getSeconds())

                var h = today.getHours() < 12 ? '오전' : '오후';

                if (hh > 12) {
                    hh = addZero(hh - 12)
                }
            
                var YY = today.getFullYear()
                var MM = addZero(today.getMonth()+1)
                var DD = addZero(today.getDate())
                var dd = dayList[today.getDay()]
            
                document.getElementById('what').innerText = h
                document.getElementById('hours').innerText = hh
                document.getElementById('min').innerText = mm
                document.getElementById('sec').innerText = ss
            
                document.getElementById('month').innerText = MM
                document.getElementById('date').innerText = DD
                document.getElementById('year').innerText = YY
                document.getElementById('day').innerText = dd
            
                function addZero(num) {
                    return (num < 10 ? '0'+num : ''+num)
                }
}, 10)
        </script>
    </body>
</html>