acc/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_delete/', views.user_delete, name="user_delete"),

    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('chpass/', views.chpass, name='chpass'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('index', views.index, name='index'),
    path('detail/<bpk>', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('update/<bpk>', views.update, name='update'),
    path('delete_content/<bpk>', views.delete_content, name='delete_content'),

    path('add_reply/<bpk>', views.add_reply, name='add_reply'),
    path('update_reply/<bpk>/<rpk>', views.update_reply, name='update_reply'),
    path('delete_reply/<bpk>/<rpk>', views.delete_reply, name='delete_reply'),

    path('likey/<bpk>', views.likey, name='likey'),
    path('unlikey/<bpk>', views.unlikey, name='unlikey'),
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<bpk>', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('tts/', include('tts.urls')),
    path('todo/', include('todo.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
from django.utils import timezone

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='writer')
    content = models.TextField()
    pubdate = models.DateTimeField(default=timezone.now)
    likey = models.ManyToManyField(User, blank=True, related_name='likey')

    def __str__(self):
        return self.subject
    
class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    pubdate = models.DateTimeField(default=timezone.now)
    comment = models.TextField()
    updated = models.TextField(default='')

    def __str__(self):
        return f'{self.board}_{self.replyer}'

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.core.paginator import Paginator
from django.contrib import messages


# Create your views here.
def index(request):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    page = request.GET.get('page', 1)
    cate = request.GET.get('cate', '')
    kw = request.GET.get('kw', '')

    if kw:
        if cate == 'title':
            b = Board.objects.filter(subject__startswith=kw)

        elif cate == 'writer':
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()

        elif cate == 'content':
            b = Board.objects.filter(content__contains=kw)
    
    else:
        b = Board.objects.all()
    
    b = b.order_by('-pubdate')

    pag = Paginator(b, 3)
    obj = pag.get_page(page)

    context = {
        'bset' : obj,
        'page' : page,
        'cate' : cate,
        'kw' : kw
    }
    return render(request, 'board/index.html', context)


def detail(request, bpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    b = Board.objects.get(id=bpk)
    c = b.reply_set.all()

    context = {
        'b' : b,
        'cset' : c
    }
    return render(request, 'board/detail.html', context)


def create(request):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    if request.method == 'POST':
        sb = request.POST.get('subject')
        cn = request.POST.get('content')
        u = request.user

        Board(subject=sb, content=cn, writer=u).save()
        return redirect('board:index')
    
    return render(request, 'board/create.html')


def update(request, bpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    
    
    b = Board.objects.get(id=bpk)

    if not b.writer == request.user:
        return redirect('board:detail', bpk)


    context = {
        'b' : b
    }

    if request.method == 'POST':
        sb = request.POST.get('subject')
        cn = request.POST.get('content')

        b.subject, b.content = sb, cn
        b.save()

        return redirect('board:detail', bpk)


    return render(request, 'board/update.html', context)

def delete_content(request, bpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    b = Board.objects.get(id=bpk)

    if request.user == b.writer:
        b.delete()

    else:
        messages.error(request, '비정상적인 접근이 확인되었습니다')

    return redirect('board:index')


def add_reply(request, bpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    com = request.GET.get('comment')
    b = Board.objects.get(id=bpk)

    Reply(board=b, replyer=request.user, comment=com).save()

    return redirect('board:detail', bpk)

def update_reply(request, bpk, rpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
        

    com = request.GET.get('comment')
    r = Reply.objects.get(id=rpk)

    if request.user == r.replyer:
        r.comment = com
        r.save()

    return redirect('board:detail', bpk)

def delete_reply(request, bpk, rpk):
    if request.user.is_anonymous:
        return redirect('acc:user_login')
    
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    
    return redirect('board:detail', bpk)


def likey(request, bpk):
    if request.user.is_anonymous:
        return request('acc:user_login')
    
    b = Board.objects.get(id=bpk)

    if not request.user in b.likey.all():
        b.likey.add(request.user)

    return redirect('board:detail', bpk)

def unlikey(request, bpk):
    if request.user.is_anonymous:
        return request('acc:user_login')
    
    b = Board.objects.get(id=bpk)

    if request.user in b.likey.all():
        b.likey.remove(request.user)

    return redirect('board:detail', bpk)

templates/board/create.html
{% extends 'base.html' %}

{% block con %}
<div class="container">

<h1><b>게시글 작성</b></h1>

<form method="post">
    {% csrf_token %}

    <div class="mb-3 mt-5">
        <label class="form-label"><b>SUBJECT</b></label>
        <input type="text" class="form-control" name="subject">
    </div>
    <div class="mb-3">
        <label class="form-label"><b>WRITER</b></label>
        <input type="text" class="form-control" value="{{ user }}" disabled>
    </div>
    <div class="mb-3">
        <label class="form-label"><b>CONTENT</b></label>
        <textarea class="form-control" style="height: 150px;" name="content"></textarea>
    </div>
    <div class="text-end mt-3">
        <button class="btn btn-dark">생성</button>
    </div>

</form>
</div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}
<div class="container">

<h1><b>{{ b.subject }}</b></h1>

<div class="row mt-5">
    <div class="col-sm-9">
        <textarea class="form-control" style="height:200px" disabled>{{ b.content }}</textarea>
    </div>
    <div class="col-sm-3">
        <img src="{{ b.writer.getpic }}" width="100%">
        <div class="text-center mt-3">
            <h5>written by <b>{{ b.writer }}</b></h5>
        </div>
        <div class="text-end mt-3">
            {{ b.pubdate|date:'Y년 m월 d일 H : i' }}
        </div>
    </div>
</div>

<div class="text-end mt-4">
    {% if not user in b.likey.all %}
    <a href="{% url 'board:likey' b.id %}" class="btn btn-secondary">좋아요</a>
    {% else %}
    <a href="{% url 'board:unlikey' b.id %}" class="btn btn-outline-secondary">좋아요 취소</a>
    {% endif %}
    <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#book">
        ✨
    </button>
    <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#reply">
        댓글
    </button>
    <a href="{% url 'board:index' %}" class="btn btn-dark">글목록</a>
    {% if user == b.writer %}
    <a href="{% url 'board:update' b.id %}" class="btn btn-dark">글수정</a>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#remove">
        글삭제
    </button>
    {% endif %}

</div>

<br><hr>

<div class="container">
    <div class="row">
        {% for i in cset %}
        <div class="col-sm-1">
            <img src="{{ i.replyer.getpic }}" style="width:90%;" id="round">
        </div>

        <div class="col-sm-9">
            <h6><b>{{i.replyer}}</b> {{i.pubdate|date:'Y년 m월 d일 H : i'}} {{i.updated}}</h6>
            <p>{{i.comment}}</p>
        </div>

        <div class="col-sm-2">
            {% if i.replyer == user %}
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#rupdate{{forloop.counter}}">
                수정
            </button>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#rdelete{{forloop.counter}}">
                삭제
            </button>
            {% endif %}
        </div>

        <br><br><br><br>

        {% empty %}
        <div class="text-center">댓글을 달아주세요!</div>
        {% endfor %}
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="remove" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                정말 삭제하시겠습니까?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                <a href="{% url 'board:delete_content' b.id %}" class="btn btn-danger">삭제</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="reply" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>댓글 추가</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'board:add_reply' b.id %}">
                <div class="modal-body">
                    <input placeholder="INPUT COMMENT" name="comment" class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <button class="btn btn-primary">등록</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% for i in cset %}
<div class="modal fade" id="rupdate{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>댓글 수정</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'board:update_reply' b.id i.id %}">
                <div class="modal-body">
                    <input placeholder="INPUT COMMENT" name="comment" class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <button class="btn btn-warning">수정</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}

{% for i in cset %}
<div class="modal fade" id="rdelete{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>댓글 삭제</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'board:add_reply' b.id %}">
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <a href="{% url 'board:delete_reply' b.id i.id %}" class="btn btn-danger">삭제</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}

<div class="modal fade" id="book" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel"><b>북마크 추가</b></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'book:create' %}">
                {% csrf_token %}

                <div class="modal-body">
                    <input type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off" name="ip">
                    <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br><br>
                    <textarea class="form-control" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;" name="con"></textarea>

                    <input type="hidden" name="nm" value="[BOARD]::{{b.subject}}">
                    <input type="hidden" name="url" value="{{request.path}}">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-outline-warning">추가</button>
                </div>

            </form>
        </div>
    </div>
</div>


<style>
    #round {
        border-radius: 50%;
        width: 70px;
        height: 70px;
        overflow: hidden;
    }
</style>

</div>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}

{% block con %}

{% load mathfilters %}

<div class="container">

<h1><b>게시판</b></h1>
    
<div class="text-end">
    <a href="{% url 'board:create' %}" class="btn btn-dark">게시글생성</a>
</div>

<table class="table table-hover mt-4">
    <thead>
        <tr class="table-dark">
            <th scope="col">NO</th>
            <th scope="col">SUBJECT</th>
            <th scope="col">SUMMARY</th>
            <th scope="col">WRITER</th>
            <th scope="col">LIKEY</th>
        </tr>
    </thead>
    <tbody>
        {% for i in bset %}
        <tr>
            <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
            <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
            <td>{{ i.content|truncatewords:10 }}</td>
            <td>{{ i.writer }}</td>
            <td>{{ i.likey.count }}</td>
        </tr>
        {% empty %}
        <tr>
            <th colspan="5">{% if kw %}검색 결과 없음{% else %} 게시글을 작성해주세요..{% endif %}</th>
        </tr>

        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if bset.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'board:index' %}?page={{bset.number|sub:1}}&cate={{cate}}&kw={{kw}}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">처음</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">이전</a>
        </li>
        {% endif %}

        {% for i in bset.paginator.page_range %}
            {% if bset.number|add:3 > i and i > bset.number|sub:3 %}
            <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{ forloop.counter }}</a></li>
            {% endif %}

        {% empty %}

        {% endfor %}

        {% if bset.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'board:index' %}?page={{bset.number|add:1}}&cate={{cate}}&kw={{kw}}">다음</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'board:index' %}?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}">마지막</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">다음</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">마지막</a>
        </li>
        {% endif %}
    </ul>
</nav>

<form>
    <div class="row">
        <div class="col-sm-2">
            <select name="cate" class="form-select">
                <option value="title" {% if cate == 'title' %}selected{% endif %}>제목</option>
                <option value="writer" {% if cate == 'writer' %}selected{% endif %}>글쓴이</option>
                <option value="content" {% if cate == 'content' %}selected{% endif %}>내용</option>
            </select>
        </div>
        <div class="col-sm-6"><input type="text" class='form-control' name="kw" value="{{kw}}"></div>
        <div class="col-sm-2"><button class="btn btn-outline-dark" style="width:100%">검색</button></div>
        <div class="col-sm-2"><a href="{% url 'board:index' %}"><button type="button" class="btn btn-outline-danger" style="width:100%">초기화</button></a></div>
    </div>
</form>


<style>
    .sub {
        text-decoration: none;
        color:black;
        font-weight: bold;
    }
    .sub:hover{
        color:red;
    }
</style>

</div>

{% endblock %}

templates/board/update.html
{% extends 'base.html' %}

{% block con %}

<div class="container">

<h1><b>게시글수정</b></h1>

<form method="post">
    {% csrf_token %}


    <div class="mb-3 mt-5">
        <label class="form-label"><b>SUBJECT</b></label>
        <input type="text" class="form-control" name="subject">
    </div>
    <div class="mb-3">
        <label class="form-label"><b>WRITER</b></label>
        <input type="text" class="form-control" disabled value="{{ b.writer }}">
    </div>
    <div class="mb-3">
        <label class="form-label"><b>CONTENT</b></label>
        <textarea class="form-control" style="height: 150px;" name="content"></textarea>
    </div>
    <div class="text-end mt-3">
        <button class="btn btn-dark">수정</button>
    </div> 

</form>
</div>
{% endblock %}